### ISSUE TITLE
A lot of empty space in head content

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/rocketchat.github.io#253]
![screen shot 2018-05-22 at 12 11 44 pm](https://user-images.githubusercontent.com/234261/40384456-fad204bc-5dd9-11e8-9b7b-dc2838a4bdc3.png)
![screen shot 2018-05-22 at 12 09 33 pm](https://user-images.githubusercontent.com/234261/40384457-fafbeb42-5dd9-11e8-86c3-7dc058281dd0.png)
![screen shot 2018-05-22 at 12 09 22 pm](https://user-images.githubusercontent.com/234261/40384458-fb1bd2e0-5dd9-11e8-81e2-bfcd5e1335c6.png)
![screen shot 2018-05-22 at 12 08 51 pm](https://user-images.githubusercontent.com/234261/40384459-fb3b5700-5dd9-11e8-8f39-42f9ff62e42a.png)
![screen shot 2018-05-22 at 12 08 36 pm](https://user-images.githubusercontent.com/234261/40384460-fb645c7c-5dd9-11e8-96b1-15c23ea218d9.png)
![screen shot 2018-05-22 at 12 08 23 pm](https://user-images.githubusercontent.com/234261/40384461-fb85535a-5dd9-11e8-940b-afff23cfefbf.png)

**Comment by isabellarussell** [comment]
Agreed. I know this is because the illustrations move with and adapt to the maximizing/minimizing of the window but they should be less buggy when they do. At the moment they sort of jump from this:

<img width="764" alt="screen shot 2018-05-23 at 10 45 19" src="https://user-images.githubusercontent.com/36157246/40417092-d6ea65ec-5e76-11e8-84d3-2dc84b48b8c0.png">


to this:

<img width="732" alt="screen shot 2018-05-23 at 10 45 29" src="https://user-images.githubusercontent.com/36157246/40417106-dd05293a-5e76-11e8-8187-ebae16a4b58a.png">

@danilowoz do you think you can fix this?

**Comment by geekgonecrazy** [comment]
@danilowoz @isabellarussell now on large screens the flare is cut off

![image](https://user-images.githubusercontent.com/51996/40455218-9d41f20c-5eb1-11e8-878e-0494645052d2.png)

:cry:

**Comment by isabellarussell** [comment]
@geekgonecrazy oh noooo!!! @danilowoz can you take a look?
