### ISSUE TITLE
Preclude Events in Related Blog Post suggestions

### ISSUE THREAD

**Issue by isabellarussell** [RocketChat/rocketchat.github.io#387]
Just spotted that events are being included in suggested Related Articles at the bottom of blog posts.
I only want actual blog posts to come up at Related Articles, **plus** I only want the suggestions to be those from the same category as the blog post the person is reading. 

Help? :) 

This is how it currently is: 
<img width="1255" alt="screen shot 2018-07-31 at 17 09 32" src="https://user-images.githubusercontent.com/36157246/43472565-a9138f22-94e5-11e8-9547-cf0740e6e963.png">

And this is where the code needs to be worked on:
![screen shot 2018-07-31 at 17 09 10](https://user-images.githubusercontent.com/36157246/43472585-b29db66c-94e5-11e8-8a58-db53572689b5.png)

**Comment by geekgonecrazy** [comment]
It looks like on line 95 its filtering the post list based on those that are in the same category.  So looks like they share a category category[0] in common.

**Comment by geekgonecrazy** [comment]
Looks like some blog posts are actually in both news and event categories.  

Like:
https://rocketchat.github.io/2017/10/27/rocket-chat-wins-all-things-open-startup-competition/
https://rocketchat.github.io/2017/07/30/karan-batra-automatic-channels-creation-in-rocketchat/

because of that event suggestions can show up in related.

If you want event suggestions removed all together... we could change line 96 to only add those that don't contain `events` as the category.

Or... remove event category from other blog posts

**Comment by ggazzo** [comment]
@isabellarussell as I can see its working as expected :x can you show your blogpost and what do you want as result? In my opinion the best idea until now: change the order of tags and keep `events` as the last (or any tag non important)
