### ISSUE TITLE
Not scaling well to portrait monitor orientation

### ISSUE THREAD

**Issue by joshsleeper** [RocketChat/rocketchat.github.io#414]
1200x1920 in my case, but I can't imagine 1080x1920 looks any better. ;)

if nothing else, you'll want to adjust the images so they don't stretch like that.

![image](https://user-images.githubusercontent.com/849941/44290013-c1574d00-a244-11e8-90e7-3bc0ea159a3d.png)

**Comment by MartinSchoeler** [comment]
That is probably being caused by the height of the image being set by view height measures, so whenever the screen grows or shrinks vertically, the image may transform in weird ways. I believe that using percentage as measure and changing it on the right resolutions breakpoints will solve this issue.

**Comment by Rodriq** [comment]
@MartinSchoeler managed to do something otherwise but it works perfectly well. 
  Sending PR soon

**Comment by joshsleeper** [comment]
Users of portrait monitors everywhere thank you!
