### ISSUE TITLE
Change blog tiles aspect ratio and text location

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/rocketchat.github.io#483]
The current blog tiles have too many variants of photo size.

![image](https://user-images.githubusercontent.com/1000217/46308131-37aed500-c58f-11e8-8ec2-297898eb8cbb.png)

Change blog tiles aspect ratio and text location to be more like 

https://blog.sketchapp.com/

**Comment by thiagosanchz** [comment]
@MartinSchoeler I discussed with Gabriel how difficult is to choose images for our blog nowadays. We can't use an illustration or another king image that isn't photos because the title/description fill almost the whole box and we have more than one size using on the grid, so is hard to create an image content for that. My idea is getting off the title and description from the image box.

**Comment by MartinSchoeler** [comment]
Closing this as it was already done.
